---
title: "R Notebook"
output: html_notebook
---

# Import data & packages

```{r}
library(tidyverse)
library(tidyboot)
library(lme4)
library(lmerTest)
library(broom.mixed)
d <- read_csv('../stickgame/human-experiments/dataFromMongo_sample3.csv')
```

# Implement exclusions, get descriptive stats

```{r}
complete_games <- d %>%
  filter(stimulus_type == 'isLong') %>%
  group_by(gameid) %>%
  tally() %>%
  filter(n == 2) %>%
  pull(gameid)

cat(length(complete_games), 'participants completed both isLong trials \n')

passed_manip_check <- d %>%
  filter(stimulus_type == 'bias') %>%
  select(stimulus_contestant, response, gameid, agent1stick, rt) %>%
  spread(stimulus_contestant, response) %>%
  filter(first > 60 | second < 40) %>%
  pull(gameid) %>%
  unique()

cat(length(passed_manip_check), 'participants passed bias manipulation check \n')

passed_rt_criterion <- d %>%
  filter(stimulus_type == 'isLong') %>%
  mutate(log_rt = log(rt),
         lower = mean(log_rt) - 2*sd(log_rt),
         upper = mean(log_rt) + 2*sd(log_rt)) %>%
  filter(log_rt > lower, log_rt < upper) %>%
  group_by(gameid) %>%
  tally() %>%
  filter(n == 2) %>%
  pull(gameid) %>%
  unique()

cat(length(passed_rt_criterion), 'participants passed RT exclusion \n')

passed_speaker_criterion <- d %>%
  filter((gameid %in% complete_games)) %>%
  filter(stimulus_type == 'speakerTrial') %>%
  select(stimulus_contestant, button_pressed, gameid) %>%
  group_by(gameid) %>%
  spread(stimulus_contestant, button_pressed) %>%
  filter(first == 4 & second == 0) %>% # & third == 2 & fourth == 0
  pull(gameid) %>%
  unique()

cat(length(passed_speaker_criterion), 'participants passed speaker exclusion \n')

ok_games  <- intersect(passed_rt_criterion, intersect(passed_speaker_criterion, passed_manip_check))
cat(length(ok_games), 'participants passed all criteria \n')
```

# Plot change in belief

```{r}
beliefChange.d <- d %>%
  filter(gameid %in% complete_games) %>%
  filter(gameid %in% ok_games) %>%
  filter(stimulus_type == 'isLong') %>%
  group_by(gameid) %>%
  select(stimulus_contestant, agent1stick, agent2stick, gameid, response) %>%
  spread(stimulus_contestant, response) %>%
  mutate(diff = second - first)

beliefChange.d %>%
  group_by(agent1stick, agent2stick) %>%
  tidyboot::tidyboot_mean(diff) %>%
  ggplot(aes(x = agent1stick, y = empirical_stat)) +
    geom_point() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    geom_smooth(method = 'lm', color = 'red') +
    geom_hline(yintercept = 0, linetype = 'dotted') +
    facet_wrap(~ agent2stick) +
    ggthemes::theme_few() +
    labs(x = 'agent 2 stick length', y = 'absolute change in belief')

beliefChange.d %>%
  group_by(agent2stick) %>%
  tidyboot::tidyboot_mean(first) %>%
  bind_rows(data.frame(agent2stick = c(0.6,0.8), empirical_stat = c(60,80), src = 'baseline')) %>%
  ggplot(aes(x = agent2stick, y = empirical_stat, color=src)) +
    geom_point() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    geom_hline(yintercept = 50, linetype = 'dotted') +
    ggthemes::theme_few() +
    labs(x = 'agent 1 stick length', y = 'belief about mean') +
    guides(color=FALSE) +
    xlim(0.5,1)+
    ylim(0,100)
```

# Look at statistics

```{r}
# This seems like the most obvious way to run the regression...?
beliefChange.d %>%
  mutate(agent1stick = agent1stick - 0.5) %>%
  lm(diff ~ agent1stick, data = .) %>%
  tidy()

# a slightly weirder alternative...
# d %>%
#   filter(gameid %in% complete_games) %>%
#   filter(gameid %in% intersect(passed_manip_check, passed_rt_criterion)) %>%
#   filter(stimulus_type == 'isLong') %>%
#   mutate(agent1stick = agent1stick - 0.5) %>%
#   lmer(response ~ agent1stick + stimulus_contestant + (1 | gameid), data = .) %>%
#   tidy()
```

# Supplemental: examine trial-level response time distribution

```{r}
d %>%
  filter(stimulus_type== 'isLong') %>%
  group_by(gameid, stimulus_type) %>%
  summarize(rt = mean(rt)) %>%
  ggplot(aes(x = log(rt))) +
    geom_histogram(bins = 15) +
    theme_bw()
```

# Supplemental: examine 2afc vs. point estimate

```{r}
d %>%
  filter(gameid %in% complete_games) %>%
  filter(gameid %in% ok_games) %>%
  filter(stimulus_type %in% c('2afc', 'meanSlider'))
```
